### ISSUE TITLE
List styling on the blog doesn't look nice anymore

### ISSUE THREAD

**Issue by kaaveland** [bring/developer-site#1695]
Seems like `<ul></ul>` would benefit from some more styling on the blog, this doesn't look so nice anymore:

<img width="699" alt="image" src="https://github.com/bring/developer-site/assets/27794/ab903953-40fe-4cb6-a8b0-b34e5fa8b320">

I've actually randomly been dropping onto the blog from google now and then over the past couple of years, which is fun and makes me feel like it's worth it!

**Comment by halvorsanden** [comment]
Oooh, an issue, how nice! 😁
We will fix it, thanks @kaaveland

**Comment by Igor-J86** [comment]
Thanks for the heads up! 👍🏼  A fix is added. ☝🏼
