### ISSUE TITLE
Developer API doesn't allow two customer ID's at the same time

### ISSUE THREAD

**Issue by yratof** [bring/developer-site#191]
Just going to leave this here in case you're the team that also manages the API / Soap for Bring

Developer API doesn't allow two customer ID's at the same time, if i have packages ID and a cargo ID, I'm not able to test a package against both of those with different IDs

**Comment by pankajagrawal16** [comment]
Hi @yratof 

You might want to check out the new version now. :). Rest now supports requesting multiple products with different customer numbers.

https://developer.bring.com/api/shipping-guide_2/#get-shipment-prices-and-estimated-delivery

**Comment by yratof** [comment]
Awesome, we've got quite a few users of https://github.com/drivdigital/bring-fraktguiden-for-woocommerce who are shipping large items with smaller items and needed that feature. We'll work on implementing it now 

@pankajagrawal16 🥇
