### ISSUE TITLE
my credentials

### ISSUE THREAD

**Issue by emilshamloo** [bring/developer-site#481]
Hello, I have a Magento 2.3.4 and I have installed "TrollWeb" installation to let my customer see the shipping info.
I am looking for these credentials:
https://prnt.sc/sfuv7h
If the second and the third are correct, then what is the "API user Id"?
Regards

**Comment by halvorsanden** [comment]
Hi, apologies for the too late answer, hoping you have gotten the answer you were looking for.
Please direct your API related questions to the comment/help section of the respective API.

This issue tracker is for problems with the site itself; Realising that this wasn’t communicated clearly enough, we have updated readme and issue template to reflect that from now on.
