### ISSUE TITLE
Unable to call postal code API multiple times

### ISSUE THREAD

**Issue by Oconrad** [bring/developer-site#615]
When calling the postal code api from our application it works fine the first time, but when calling it again 10 seconds later, it fails with status code 429 Too Many Requests and a CORS error message. However, when we use Postman we are successfully able to call the api multiple times. For both our application and Postman, we use the same authentication credentials. 
<img width="797" alt="0378" src="https://user-images.githubusercontent.com/9113425/106861413-02b66e00-66c6-11eb-9bb4-01fff5fed1ee.PNG">
<img width="648" alt="0378_1" src="https://user-images.githubusercontent.com/9113425/106861419-034f0480-66c6-11eb-8506-1b42172ed62d.PNG">
<img width="827" alt="0379" src="https://user-images.githubusercontent.com/9113425/106861421-03e79b00-66c6-11eb-8bc7-86538bb600e2.PNG">
<img width="810" alt="0379_1" src="https://user-images.githubusercontent.com/9113425/106861422-03e79b00-66c6-11eb-8b51-94e6268dcccc.PNG">

**Comment by halvorsanden** [comment]
Hi, please direct your API related questions to the comment/help section of the API: https://developer.bring.com/api/postal-code/ There you will reach the right people.
This issue tracker is for problems with the site itself; Realising that this wasn’t communicated clearly enough, we have updated readme and issue template to reflect that from now on.
