### ISSUE TITLE
Woocommerce height and length mix up.

### ISSUE THREAD

**Issue by StanFroggo** [bring/developer-site#769]
NOTE: For API related bugs and questions, use the comments section on the respective API.

### Issue description
By default, woocommerce dimensions are described as LxWxH . Current, Bring plugin mixes up Lenght and Height and the debug log parameter array inputs wrong information. For example, my product dimensions are:

50 x 76 x 100 (Length x Width x Height). Bring plugins uses them like this (which is wrong):

Parameters: 
Array
(
    [clientUrl] => localhost
    [frompostalcode] => 1540
    [fromcountry] => NO
    [topostalcode] => 1560
    [tocountry] => NO
    [postingatpostoffice] => false
    [language] => en
    **[length0]** => 100
    [width0] => 76
    **[height0]** => 50
    [weight0] => 2000
)

This causes miss calculation of the price from-to by post code.

**Comment by halvorsanden** [comment]
Closing this as well, see other comment: https://github.com/bring/developer-site/issues/770#issuecomment-841078440
