### ISSUE TITLE
Different outcome using Bring plugin and using cURL

### ISSUE THREAD

**Issue by StanFroggo** [bring/developer-site#770]
This is kinda of a weird issue. My client asked me to make as simple post code price checker. Everything works fine, but I get different prices if i use my cURL request and Bring uses his. It only happens with the code **( 5300 )** . Here's what I mean. This the output of the debug log from woocommerce. If you look closely, the cost is 877 NOK.

**Can this be some sort of an issue or Bring Woocommerce plugin calculates something different? This ONLY happens using code 5300**

------------

05-12-2021 @ 15:12:58 - Request url: https://api.bring.com/shippingguide/v2/products?clientUrl=localhost&frompostalcode=1540&fromcountry=NO&topostalcode=1560&tocountry=NO&postingatpostoffice=false&language=en&length0=100&width0=76&height0=50&weight0=2000&product=5300
05-12-2021 @ 15:12:58 - Parameters: 
Array
(
    [clientUrl] => localhost
    [frompostalcode] => 1540
    [fromcountry] => NO
    [topostalcode] => 1560
    [tocountry] => NO
    [postingatpostoffice] => false
    [language] => en
    [length0] => 100
    [width0] => 76
    [height0] => 50
    [weight0] => 2000
)

05-12-2021 @ 15:12:58 - Response: 
{
    "traceMessages": [],
    "consignments": [
        {
            "products": [
                {
                    "id": "5300",
                    "customerNumber": "88386891",
                    "productionCode": "5300",
                    "shippingWeight": 109,
                    "guiInformation": {
                        "sortOrder": "222",
                        "mainDisplayCategory": "Cargo",
                        "subDisplayCategory": "To business customers",
                        "displayName": "Business partload",
                        "productName": "Business partload",
                        "descriptionText": "The goods are shipped directly from the sender to the recipient and delivered to the door between 8 a.m. and 4 p.m.",
                        "helpText": "The goods are shipped directly from the sender to the recipient and delivered to the door between 8 a.m. and 4 p.m.If the shipment cannot be delivered on the first attempt, the recipient is contacted to agree on a new delivery date. ",
                        "shortName": "Business partload",
                        "productURL": "",
                        "deliveryType": "Door",
                        "maxWeightInKgs": "35000"
                    },
                    "price": {
                        "listPrice": {
                            "priceWithoutAdditionalServices": {
                                "amountWithoutVAT": "1420.00",
                                "vat": "355.00",
                                "amountWithVAT": "1775.00"
                            },
                            "priceWithAdditionalServices": {
                                "amountWithoutVAT": "1420.00",
                                "vat": "355.00",
                                "amountWithVAT": "1775.00"
                            },
                            "currencyCode": "NOK"
                        },
                        "netPrice": {
                            "priceWithoutAdditionalServices": {
                                "amountWithoutVAT": "877.00",
                                "vat": "219.25",
                                "amountWithVAT": "1096.25"
                            },
                            "priceWithAdditionalServices": {
                                "amountWithoutVAT": "877.00",
                                "vat": "219.25",
                                "amountWithVAT": "1096.25"
                            },
                            "currencyCode": "NOK",
                            "netPriceFailed": true
                        }
                    },
                    "expectedDelivery": {
                        "workingDays": "3",
                        "userMessage": "",
                        "formattedExpectedDeliveryDate": "20.05.2021",
                        "expectedDeliveryDate": {
                            "year": "2021",
                            "month": "5",
                            "day": "20"
                        },
                        "alternativeDeliveryDates": [],
                        "formattedEarliestPickupDate": "14.05.2021 08:00",
                        "earliestPickupDate": {
                            "year": "2021",
                            "month": "5",
                            "day": "14",
                            "hour": "8",
                            "minute": "0"
                        }
                    }
                }
            ]
        }
    ],
    "uniqueId": "0147a7e7-1c2a-4e9b-8767-707064d154d5"
}
05-12-2021 @ 15:12:58 - Rates found: Array
(
    [0] => Array
        (
            [id] => bring_fraktguiden
            [bring_product] => 5300
            [cost] => 877
            [label] => Business partload: The goods are shipped directly from the sender to the recipient and delivered to the door between 8 a.m. and 4 p.m.
        )

)

But if you query using the bring API directly, 

https://api.bring.com/shippingguide/v2/products?clientUrl=localhost&frompostalcode=1540&fromcountry=NO&topostalcode=1560&tocountry=NO&postingatpostoffice=false&language=en&length0=100&width0=76&height0=50&weight0=2000&product=5300

You will get another price **here**

 "price": {
                        "listPrice": {
                            "priceWithoutAdditionalServices": {
                                "amountWithoutVAT": "1420.00",
                                "vat": "355.00",
                                "amountWithVAT": "1775.00"
                            },
                            "priceWithAdditionalServices": {
                                "amountWithoutVAT": "1420.00",
                                "vat": "355.00",
                                "amountWithVAT": "1775.00"
                            },
                            "currencyCode": "NOK"
                        },
                        "netPrice": {
                            "priceWithoutAdditionalServices": {
                                "amountWithoutVAT": "1261.00",
                                "vat": "315.25",
                                "amountWithVAT": "1576.25"
                            },
                            "priceWithAdditionalServices": {
                                "amountWithoutVAT": "1261.00",
                                "vat": "315.25",
                                "amountWithVAT": "1576.25"
                            },
                            "cargoAgreementPrices": [
                                {
                                    "agreementName": "GrossPrice",
                                    "agreementNumber": "-1",
                                    "subAgreementNumber": "-1",
                                    "subAgreementName": ""
                                }
                            ],
                            "currencyCode": "NOK"
                        }
                    }

**Comment by halvorsanden** [comment]
@StanFroggo If you have issues with any of the APIs, please ask in the support section of the respective API – which I see you have done for your other question – that is being answered by people working directly with the APIs. The Github issues are for the documentation site itself.

Also, the Woocommerce plugin in not official, made or supported by Bring, so you have to direct your questions regarding that to those who make it.

I’m closing both issues.
